### ISSUE TITLE
Not working on Paper 1.20.2

### ISSUE THREAD

**Issue by envizar** [hotpocket184/skript-advancements#34]
```
[09:31:24 INFO]: [Skript-Advancements] Enabling Skript-Advancements v1.5.7
[09:31:24 ERROR]: Error occurred while enabling Skript-Advancements v1.5.7 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.commonEnablePreDatabase(AdvancementMain.java:183) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.enableSQLite(AdvancementMain.java:120) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onEnable(SkriptAdvancements.java:48) ~[skriptadvancements-1.5.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-206]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at com.shanebeestudios.briggy.api.util.Utils.reloadCommands(Utils.java:26) ~[SkBriggy-master-1.0.0.jar:?]
        at com.shanebeestudios.briggy.api.BrigCommand.build(BrigCommand.java:93) ~[SkBriggy-master-1.0.0.jar:?]
        at com.shanebeestudios.briggy.skript.structures.StructBrigCommand.load(StructBrigCommand.java:160) ~[SkBriggy-master-1.0.0.jar:?]
        at ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566) ~[Skript-nightly.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558) ~[Skript-nightly.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511) ~[Skript-nightly.jar:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457) ~[Skript-nightly.jar:?]
        at ch.njol.skript.Skript$1.run(Skript.java:814) ~[Skript-nightly.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1097) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-206]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.<clinit>(AdvancementUtils.java:46) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.load(AdvancementMain.java:93) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onLoad(SkriptAdvancements.java:41) ~[skriptadvancements-1.5.7.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-206]
        ... 2 more
[09:31:24 INFO]: [Skript-Advancements] Disabling Skript-Advancements v1.5.7
[09:31:24 ERROR]: Error occurred (in the plugin loader) while disabling Skript-Advancements v1.5.7 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.disable(AdvancementMain.java:236) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onDisable(SkriptAdvancements.java:76) ~[skriptadvancements-1.5.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-206]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
        at com.shanebeestudios.briggy.api.util.Utils.reloadCommands(Utils.java:26) ~[SkBriggy-master-1.0.0.jar:?]
        at com.shanebeestudios.briggy.api.BrigCommand.build(BrigCommand.java:93) ~[SkBriggy-master-1.0.0.jar:?]
        at com.shanebeestudios.briggy.skript.structures.StructBrigCommand.load(StructBrigCommand.java:160) ~[SkBriggy-master-1.0.0.jar:?]
        at ch.njol.skript.ScriptLoader.lambda$loadScripts$8(ScriptLoader.java:566) ~[Skript-nightly.jar:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:558) ~[Skript-nightly.jar:?]
        at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511) ~[Skript-nightly.jar:?]
        at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457) ~[Skript-nightly.jar:?]
        at ch.njol.skript.Skript$1.run(Skript.java:814) ~[Skript-nightly.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1097) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-206]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.util.AdvancementUtils.<clinit>(AdvancementUtils.java:46) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.libs.com.fren_gor.ultimateAdvancementAPI.AdvancementMain.load(AdvancementMain.java:93) ~[skriptadvancements-1.5.7.jar:?]
        at me.hotpocket.skriptadvancements.SkriptAdvancements.onLoad(SkriptAdvancements.java:41) ~[skriptadvancements-1.5.7.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:40) ~[paper-1.20.2.jar:git-Paper-206]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.2.jar:git-Paper-206]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.loadPlugins(CraftServer.java:512) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.20.2.jar:git-Paper-206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-206]
        ... 2 more
```

**Comment by erenkarakal** [comment]
Released a new update.
